// Data setters
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_BY_ID = 'SET_PRODUCT_BY_ID';
export const SET_CATEGORIES = 'SET_CATEGORIES';

// Status setters
// Products
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
// Product detail
export const FETCH_PRODUCT_BY_ID_BEGIN = 'FETCH_PRODUCT_BY_ID_BEGIN';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILED = 'FETCH_PRODUCT_BY_ID_FAILED';
// Delete product
export const RESET_DELETED_BY_ID_STATUS = 'RESET_DELETED_BY_ID_STATUS';
export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
// Change product in DB
export const CHANGE_PRODUCTS_IN_DB_BEGIN = 'CHANGE_PRODUCTS_IN_DB_BEGIN';
export const CHANGE_PRODUCTS_IN_DB_SUCCESS = 'CHANGE_PRODUCTS_IN_DB_SUCCESS';
export const CHANGE_PRODUCTS_IN_DB_FAILED = 'CHANGE_PRODUCTS_IN_DB_FAILED';
// Get categories from DB
export const GET_CATEGORIES_BEGIN = 'GET_CATEGORIES_BEGIN';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
// Get categories from DB
export const ADD_CATEGORY_BEGIN = 'ADD_CATEGORY_BEGIN';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';
// Local status
export const RESET_FORM_STATUS = 'RESET_FORM_STATUS';
// Async status
export const SEND_FORM_BEGIN = 'SEND_FORM_BEGIN';
export const SEND_FORM_SUCCESS = 'FETCH_DETAIL_SUCCESS';
export const SEND_FORM_FAILURE = 'FETCH_DETAIL_FAILURE';
